### PR TITLE
compose: fix lookupproxy deployment

### PR DESCRIPTION
**Pull request by rjw57**
The lookupproxy compose configuration was only semi-functional. Since we're going to need to re-deploy the lookupproxy in development *anyway* to bring in the django-automationoauth fixes, fix up the configuration so that it can use the upstream production image.

This should further reduce CircleCI build times and also means that lookupproxy actually works in development. Previously it didn't since the OAuth2 configuration was not being set.

### CODE REVIEW

**Comment by abrahammartin** [comment]
This is relying on the docker hub's lookupproxy, the last time we checked that wasn't working properly and it was not building for every push to master and we had to quick it manually. Has this changed now?

**Comment by rjw57** [comment]
It seems to have worked last time I checked, but in any case if the lookupproxy image isn't building, then that's a separate issue: https://github.com/uisautomation/lookupproxy/issues/27

**Comment by abrahammartin** [comment]
We can test with https://github.com/uisautomation/lookupproxy/pull/26

**Comment by rjw57** [comment]
True, I just added a new automated build rule for a new branch and was going to push that branch to see, but merging uisautomation/lookupproxy#26 would work just as well. I just worry about merging that because we've got no way to safely test it at the moment.

**Pull request merged**
